### ISSUE TITLE
NodeJS support

### ISSUE THREAD

**Issue by W4G1** [ColonelParrot/jscanify#1]
On the website it says:
> It can run in the browser or on a server with NodeJS.  

When importing the library in Node however, I get the following error:
```
Uncaught ReferenceError: document is not defined
```

**Comment by ColonelParrot** [comment]
Thanks for the report!
I see the issue  and I'll get a patch out as soon as possible.

**Comment by ColonelParrot** [comment]
Unfortunately, I'm swamped at the moment. Could probably get a patch out by early May.
Thanks for the patience.

**Comment by ColonelParrot** [comment]
Hello,
Thanks for the patience! This has now been patched in [v1.1.0](https://github.com/ColonelParrot/jscanify/releases/tag/v1.1.0).
Make sure to check the wiki section [Use on NodeJS](https://github.com/ColonelParrot/jscanify/wiki#use-on-nodejs) - the usage is slightly different.

If you run into any problems please let me know 👍
