### ISSUE TITLE
Do you have the document detection in real time while using the camera to get the photo through MediaCapture API ?

### ISSUE THREAD

**Issue by adantart** [ColonelParrot/jscanify#12]
Do you have the document detection in real time while using the camera to get the photo through MediaCapture API ?
thank you !

**Comment by ColonelParrot** [comment]
Have you tried the one on the README? It's [here](https://github.com/ColonelParrot/jscanify#highlighting-paper-in-user-camera)

**Comment by adantart** [comment]
Yes, sorry, I should have said it ... I tried it but it seems is broken since I see my webcam, and two divs (canvas and result) with just a zoomed in part of the camera (the top left part)

**Comment by micuoiz** [comment]
The problem is that the width and height of both canvas are not set. Get the canvas elements and assign the mentioned properties. After that it should work.
Like: `canvas.width = video.videoWidth`.

**Comment by adantart** [comment]
It's because the canvas width and height. By default is always 300 x 150

**Comment by ColonelParrot** [comment]
Interesting. I haven't taken a look at the specifics yet, but have you tried setting the dimensions of `result` to that of `resultCanvas`?

**Comment by adantart** [comment]
Yes, I did it that way forcing the width/height (setting them by javascript). No problem in that.
Thank you !
