### ISSUE TITLE
Poor Image Quality

### ISSUE THREAD

**Issue by justnixx** [ColonelParrot/jscanify#19]
Hi @ColonelParrot, thank you for this awesome library. I'm currently using it in a personal project, but I've noticed that the image quality is poor. I've attached the scanned document images below for reference. 

I made a small modification to the extractPaper() method, but even before that, the quality was not satisfactory. Any suggestions or tips would be highly appreciated.

```JavaScript
// Calculate the aspect ratio of the original document
const aspectRatio = img.cols / img.rows;

// Calculate the corresponding height to maintain the aspect ratio
const calculatedHeight = Math.round(resultWidth / aspectRatio);
```

![https___fb3465873dcfdfd46149d03d5c93061e cdn bubble io_f1699873545002x420828177219472640_image-1699873543332](https://github.com/ColonelParrot/jscanify/assets/45858998/79953f09-21bf-4e56-b929-a048ed6a7a30)
I applied filter here

![image-1699873103017](https://github.com/ColonelParrot/jscanify/assets/45858998/043df2c7-d87e-4764-9077-1178760a348c)

![image-1699884609056](https://github.com/ColonelParrot/jscanify/assets/45858998/5c81b849-ae6a-4511-bce9-1bc784924ed2)

**Comment by ColonelParrot** [comment]
Is this a software or hardware issue? Is the image coming from the camera blurry?

**Comment by justnixx** [comment]
software

**Comment by justnixx** [comment]
What I'm looking to achieve is:

- a. The best possible image quality.
- b. Dynamic width and height: I want the paper size to be determined by the image, rather than inputting dimensions manually, as not all documents are the same size.

Here's a demo link: https://jsscanner.netlify.app

**Comment by robinreckmann** [comment]
In the video constraints, did you try adding something like the following?

```
video: {
            width: { ideal: 99999 },
            height: { ideal: 99999 },
            facingMode: "environment"
        }
```

In the example you provided it looks like this:
```
navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'environment' },
      });
```

**Comment by justnixx** [comment]
@robinreckmann Ah, no. Let me try that now.

**Comment by ColonelParrot** [comment]
Glad you could figure it out! If you come across any other issues, do let me know 👍
