### ISSUE TITLE
extractPaper not working with cluttered background

### ISSUE THREAD

**Issue by kirley** [ColonelParrot/jscanify#21]
I'm very impressed by jscanify and I really appreciate that you open sourced your work. 

I have two examples where a cluttered background breaks the `extractPaper` logic to find the paper in the image.   I think this is an edge case (no pun intended) but perhaps these can help you future improve the algorithm.

![IMG_3553](https://github.com/ColonelParrot/jscanify/assets/1103613/bde19e54-075d-4edc-b006-5d69e7cb6b42)
![IMG_3554](https://github.com/ColonelParrot/jscanify/assets/1103613/84245818-6d8b-4b7e-acea-9dccb5fab48a)

**Comment by ColonelParrot** [comment]
Thanks for reaching out from Reddit!

BTW I just released a [debugging tool](https://colonelparrot.github.io/jscanify/tester.html) that will make it much quicker to test the detection on specific images. The screenshots that I've added below were of the debugging tool.

For the second image, I'm not seeing any issue :). Here's a screenshot:
![image](https://github.com/ColonelParrot/jscanify/assets/65585002/15ca5740-37f6-4b85-bb3d-7501d5fa00d1)

The lib does have some trouble detecting the first one though:
![image](https://github.com/ColonelParrot/jscanify/assets/65585002/99f3ee3e-5d24-4348-af74-9328d68e5e8c)

If I were to guess the problem there would be two:
- the glare is extending the boundary of the contour
- that, compounded with the fact that there are lots of other white objects in the frame


This is a tough problem to solve. If you're building a scanner app for the users, I would suggest you simply ask them to place the document in a better spot without glare and a solid background.
If you're using this to process these specific images, you may need to modify the thresholds a little bit.

If the path you choose to take is the latter, let me know and I'll guide you through it.

**Comment by kirley** [comment]
Thanks for you comments.  The debugger is fantastic!
