### ISSUE TITLE
React js import support?

### ISSUE THREAD

**Issue by kennarddh** [ColonelParrot/jscanify#7]
Expected Usage

```ts
import jscanify from 'jscanify'
```

**Comment by ColonelParrot** [comment]
Hello,
We have provided an example of how to use it in React. Were you experiencing a problem with it?

**Comment by kennarddh** [comment]
Yeah you need to include it in the `index.html` can you publish to use with import like

```js
import jscanify from 'jscanify'
```

**Comment by ColonelParrot** [comment]
Hello,
This is on my bucket list, but it will take quite some time to get a stable solution.
For now, I would still recommend using the official solution.

As always, if you need any help, feel free to ask!

**Comment by alexkev** [comment]
import jscanify from 'jscanify/src/jscanify'; worked for me
