### ISSUE TITLE
Doesn't work in web (React)

### ISSUE THREAD

**Issue by Avinamor** [ColonelParrot/jscanify#8]
Hey!

I was trying to use the package on the FE side (React) but faced several issues. If I install it via npm (in my case pnpm, but I guess it doesn't matter) it fails with the error. It requires Node.js variable **process**. 
If I use it via CDN, its dependency - opencv.js requires Node.js variable **process**. 

Error: Uncaught ReferenceError: process is not defined

Could you please clarify if it's possible to use this lib in React? If you do - please clarify the steps to use it. 
The React example didn't help...

**Comment by ColonelParrot** [comment]
Duplicate of #7

**Comment by ColonelParrot** [comment]
Hello,
This is on my bucket list, but don't expect a stable fix soon.
